name: Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
    paths-ignore: ['README.md', 'docs/**']

jobs:
  swiftformat:
    name: SwiftFormat
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - run: swiftformat . --lint --quiet --reporter github-actions-log

  swiftlint:
    name: SwiftLint
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: Install SwiftLint
      run: brew install swiftlint
    - run: swiftlint --strict --quiet --reporter github-actions-logging

  release:
    name: Build Binary
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}
        restore-keys: ${{ runner.os }}-spm-
    - name: Select Xcode 15.3
      run: sudo xcode-select -s '/Applications/Xcode_15.3.app'
    - name: Build
      run: swift build -c release
